In [2]:
import numpy as np

In [10]:
A = np.array([[1, 5],[4, -2]])
A

array([[ 1,  5],
       [ 4, -2]])

In [11]:
B = np.array([[2, -1],[7, 6]])
B

array([[ 2, -1],
       [ 7,  6]])

In [6]:
A + B

array([[ 3,  4],
       [11,  4]])

In [7]:
A - B

array([[-1,  6],
       [-3, -8]])

In [8]:
np.dot(A, B)
#行列の積

array([[ 37,  29],
       [ -6, -16]])

In [9]:
A * B
#要素同士の掛け算

array([[  2,  -5],
       [ 28, -12]])

In [13]:
A = np.array([[1, 5, -2], [4, 0, -3], [-8, 2, 6]])
A

array([[ 1,  5, -2],
       [ 4,  0, -3],
       [-8,  2,  6]])

In [14]:
A.sum()

5

In [15]:
A.max()

6

In [16]:
A.min()

-8

In [17]:
A.mean()

0.5555555555555556

In [20]:
np.average(A)

0.5555555555555556

In [21]:
np.median(A)

1.0

In [22]:
np.var(A)

17.358024691358025

In [24]:
np.std(A)

4.166296279833928

In [31]:
A = np.array([[1, 5], [4, -2]])

In [32]:
#0でなければ逆行列が存在する
a = np.linalg.det(A)
a

-22.000000000000004

In [33]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.09090909,  0.22727273],
       [ 0.18181818, -0.04545455]])

In [35]:
np.dot(A, A_inv)

array([[ 1.00000000e+00, -2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00]])

In [36]:
import pandas as pd

In [53]:
df = pd.read_csv('weather.csv')

In [54]:
df.head(3)

年月日  平均気温(℃) 平均気温(℃).1 平均気温(℃).2  最高気温(℃) 最高気温(℃).1 最高気温(℃).2  \
0         NaN      NaN      品質情報      均質番号      NaN      品質情報      均質番号   
1  2019/12/14      9.3         8         1     15.9         8         1   
2  2019/12/15      7.8         8         1     11.1         8         1   

   最低気温(℃) 最低気温(℃).1 最低気温(℃).2  ...  平均雲量(10分比).2 平均蒸気圧(hPa) 平均蒸気圧(hPa).1  \
0      NaN      品質情報      均質番号  ...          均質番号        NaN         品質情報   
1      3.2         8         1  ...             1        NaN            0   
2      4.0         8         1  ...             1        NaN            0   

   平均蒸気圧(hPa).2 平均風速(m/s) 平均風速(m/s).1  平均風速(m/s).2 日照時間(時間) 日照時間(時間).1  \
0          均質番号       NaN        品質情報         均質番号      NaN       品質情報   
1             1       2.0           8            1      8.9          8   
2             1       2.3           8            1      6.3          8   

   日照時間(時間).2  
0        均質番号  
1           1  
2           1  

[3 rows x 28 columns]

In [55]:
df.tail(10)

年月日  平均気温(℃) 平均気温(℃).1 平均気温(℃).2  最高気温(℃) 最高気温(℃).1 最高気温(℃).2  \
358   2020/12/5      6.0         8         1      7.3         8         1   
359   2020/12/6      8.0         8         1     13.3         8         1   
360   2020/12/7      9.0         8         1     16.0         8         1   
361   2020/12/8     10.4         8         1     16.0         8         1   
362   2020/12/9      9.2         8         1     11.2         8         1   
363  2020/12/10      8.7         8         1     11.1         8         1   
364  2020/12/11      9.2         8         1     13.8         8         1   
365  2020/12/12     10.4         8         1     14.0         8         1   
366  2020/12/13      8.6         8         1     14.4         8         1   
367  2020/12/14      7.8         8         1     12.2         8         1   

     最低気温(℃) 最低気温(℃).1 最低気温(℃).2  ...  平均雲量(10分比).2 平均蒸気圧(hPa) 平均蒸気圧(hPa).1  \
358      4.3         8         1  ...             1        NaN            0   
359      4.5         8         1  ...             1        NaN            0   
360      4.2         8         1  ...             1        NaN            0   
361      4.6         8         1  ...             1        NaN            0   
362      8.3         8         1  ...             1        NaN            0   
363      6.0         8         1  ...             1        NaN            0   
364      3.5         8         1  ...             1        NaN            0   
365      8.0         8         1  ...             1        NaN            0   
366      4.4         8         1  ...             1        NaN            0   
367      4.4         8         1  ...             1        NaN            0   

     平均蒸気圧(hPa).2 平均風速(m/s) 平均風速(m/s).1  平均風速(m/s).2 日照時間(時間) 日照時間(時間).1  \
358             1       1.4           8            1      0.0          8   
359             1       1.0           8            1      3.8          8   
360             1       0.7           8            1      9.0          8   
361             1       1.3           8            1      6.9          8   
362             1       1.4           8            1      0.0          8   
363             1       1.4           8            1      0.0          8   
364             1       0.8           8            1      4.3          8   
365             1       1.4           8            1      1.4          8   
366             1       1.0           8            1      5.5          8   
367             1       1.9           8            1      4.4          8   

     日照時間(時間).2  
358           1  
359           1  
360           1  
361           1  
362           1  
363           1  
364           1  
365           1  
366           1  
367           1  

[10 rows x 28 columns]

In [56]:
df.columns

Index(['年月日', '平均気温(℃)', '平均気温(℃).1', '平均気温(℃).2', '最高気温(℃)', '最高気温(℃).1',
       '最高気温(℃).2', '最低気温(℃)', '最低気温(℃).1', '最低気温(℃).2', '降水量の合計(mm)',
       '降水量の合計(mm).1', '降水量の合計(mm).2', '最深積雪(cm)', '最深積雪(cm).1', '最深積雪(cm).2',
       '平均雲量(10分比)', '平均雲量(10分比).1', '平均雲量(10分比).2', '平均蒸気圧(hPa)',
       '平均蒸気圧(hPa).1', '平均蒸気圧(hPa).2', '平均風速(m/s)', '平均風速(m/s).1',
       '平均風速(m/s).2', '日照時間(時間)', '日照時間(時間).1', '日照時間(時間).2'],
      dtype='object')

In [57]:
df = df[['年月日',
 '平均気温(℃)',
 '最高気温(℃)',
 '最低気温(℃)',
 '降水量の合計(mm)',
 '最深積雪(cm)',
 '平均雲量(10分比)',
 '平均蒸気圧(hPa)',
 '平均風速(m/s)',
 '日照時間(時間)']][1:]
df

年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)  平均雲量(10分比)  \
1    2019/12/14      9.3     15.9      3.2         0.0       NaN         NaN   
2    2019/12/15      7.8     11.1      4.0         0.0       NaN         NaN   
3    2019/12/16      6.9     12.5      1.3         0.0       NaN         NaN   
4    2019/12/17      8.2     10.3      5.7         2.0       NaN         NaN   
5    2019/12/18      9.9     15.0      4.8         0.0       NaN         NaN   
..          ...      ...      ...      ...         ...       ...         ...   
363  2020/12/10      8.7     11.1      6.0         0.5       NaN         NaN   
364  2020/12/11      9.2     13.8      3.5         0.0       NaN         NaN   
365  2020/12/12     10.4     14.0      8.0         0.0       NaN         NaN   
366  2020/12/13      8.6     14.4      4.4         0.0       NaN         NaN   
367  2020/12/14      7.8     12.2      4.4         0.0       NaN         NaN   

     平均蒸気圧(hPa)  平均風速(m/s)  日照時間(時間)  
1           NaN        2.0       8.9  
2           NaN        2.3       6.3  
3           NaN        1.1       8.9  
4           NaN        1.1       0.2  
5           NaN        1.2       4.3  
..          ...        ...       ...  
363         NaN        1.4       0.0  
364         NaN        0.8       4.3  
365         NaN        1.4       1.4  
366         NaN        1.0       5.5  
367         NaN        1.9       4.4  

[367 rows x 10 columns]

In [58]:
df.dtypes

年月日            object
平均気温(℃)       float64
最高気温(℃)       float64
最低気温(℃)       float64
降水量の合計(mm)    float64
最深積雪(cm)      float64
平均雲量(10分比)    float64
平均蒸気圧(hPa)    float64
平均風速(m/s)     float64
日照時間(時間)      float64
dtype: object

In [59]:
df.shape

(367, 10)

In [60]:
df.columns

Index(['年月日', '平均気温(℃)', '最高気温(℃)', '最低気温(℃)', '降水量の合計(mm)', '最深積雪(cm)',
       '平均雲量(10分比)', '平均蒸気圧(hPa)', '平均風速(m/s)', '日照時間(時間)'],
      dtype='object')

In [61]:
df.index

RangeIndex(start=1, stop=368, step=1)

In [62]:
df.iloc[4:10, 2:6]

最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)
5      15.0      4.8         0.0       NaN
6       9.7      7.9         1.0       NaN
7      15.8      5.7         0.0       NaN
8       8.4      6.5         0.0       NaN
9       9.8      4.2        21.0       NaN
10     12.1      3.6         9.5       NaN

In [76]:
df_people = pd.read_csv('people.csv')
df_people

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
2   35  31    Suzuki       Japan
3   16  20      John     America
4   28  11       Kim       Korea

In [77]:
df_people[df_people['nationality'] == 'America']

age  id  name nationality
1   21  33  Mike     America
3   16  20  John     America

In [78]:
df_people.query('nationality == "America"')

age  id  name nationality
1   21  33  Mike     America
3   16  20  John     America

In [79]:
df_people['age'] >= 20

0     True
1     True
2     True
3    False
4     True
Name: age, dtype: bool

In [80]:
df_people['age'] < 30

0     True
1     True
2    False
3     True
4     True
Name: age, dtype: bool

In [82]:
df_people[(df_people['age'] >= 20) & (df_people['age'] < 30)]

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
4   28  11       Kim       Korea

In [83]:
df_people.query('age >= 20 & age < 30')

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
4   28  11       Kim       Korea

In [84]:
df_people['age'].unique()

array([26, 21, 35, 16, 28], dtype=int64)

In [85]:
df_people['nationality'].unique()

array(['Japan', 'America', 'Korea'], dtype=object)

In [87]:
df_people.drop_duplicates(subset='nationality')

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
4   28  11       Kim       Korea

In [90]:
df

年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)  平均雲量(10分比)  \
1    2019/12/14      9.3     15.9      3.2         0.0       NaN         NaN   
2    2019/12/15      7.8     11.1      4.0         0.0       NaN         NaN   
3    2019/12/16      6.9     12.5      1.3         0.0       NaN         NaN   
4    2019/12/17      8.2     10.3      5.7         2.0       NaN         NaN   
5    2019/12/18      9.9     15.0      4.8         0.0       NaN         NaN   
..          ...      ...      ...      ...         ...       ...         ...   
363  2020/12/10      8.7     11.1      6.0         0.5       NaN         NaN   
364  2020/12/11      9.2     13.8      3.5         0.0       NaN         NaN   
365  2020/12/12     10.4     14.0      8.0         0.0       NaN         NaN   
366  2020/12/13      8.6     14.4      4.4         0.0       NaN         NaN   
367  2020/12/14      7.8     12.2      4.4         0.0       NaN         NaN   

     平均蒸気圧(hPa)  平均風速(m/s)  日照時間(時間)  
1           NaN        2.0       8.9  
2           NaN        2.3       6.3  
3           NaN        1.1       8.9  
4           NaN        1.1       0.2  
5           NaN        1.2       4.3  
..          ...        ...       ...  
363         NaN        1.4       0.0  
364         NaN        0.8       4.3  
365         NaN        1.4       1.4  
366         NaN        1.0       5.5  
367         NaN        1.9       4.4  

[367 rows x 10 columns]

In [92]:
df.columns

Index(['年月日', '平均気温(℃)', '最高気温(℃)', '最低気温(℃)', '降水量の合計(mm)', '最深積雪(cm)',
       '平均雲量(10分比)', '平均蒸気圧(hPa)', '平均風速(m/s)', '日照時間(時間)'],
      dtype='object')

In [93]:
df.rename(columns = {
 '平均気温(℃)': '平均気温',
 }).head()

年月日  平均気温  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)  平均雲量(10分比)  \
1  2019/12/14   9.3     15.9      3.2         0.0       NaN         NaN   
2  2019/12/15   7.8     11.1      4.0         0.0       NaN         NaN   
3  2019/12/16   6.9     12.5      1.3         0.0       NaN         NaN   
4  2019/12/17   8.2     10.3      5.7         2.0       NaN         NaN   
5  2019/12/18   9.9     15.0      4.8         0.0       NaN         NaN   

   平均蒸気圧(hPa)  平均風速(m/s)  日照時間(時間)  
1         NaN        2.0       8.9  
2         NaN        2.3       6.3  
3         NaN        1.1       8.9  
4         NaN        1.1       0.2  
5         NaN        1.2       4.3

In [96]:
df.columns = [
    '年月日',
    '平均気温(℃)',
    '最高気温(℃)',
    '最低気温(℃)',
    '降水量の合計(mm)',
    '最深積雪(cm)',
    '平均雲量(10分比)',
    '平均蒸気圧(hPa)',
    '平均風速(m/s)',
    '日照時間(時間)'
]

In [97]:
df.head()

年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)  平均雲量(10分比)  \
1  2019/12/14      9.3     15.9      3.2         0.0       NaN         NaN   
2  2019/12/15      7.8     11.1      4.0         0.0       NaN         NaN   
3  2019/12/16      6.9     12.5      1.3         0.0       NaN         NaN   
4  2019/12/17      8.2     10.3      5.7         2.0       NaN         NaN   
5  2019/12/18      9.9     15.0      4.8         0.0       NaN         NaN   

   平均蒸気圧(hPa)  平均風速(m/s)  日照時間(時間)  
1         NaN        2.0       8.9  
2         NaN        2.3       6.3  
3         NaN        1.1       8.9  
4         NaN        1.1       0.2  
5         NaN        1.2       4.3

In [100]:
df.sort_values('最高気温(℃)', ascending=True)

年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)  平均雲量(10分比)  \
55    2020/2/6      2.3      5.5     -1.3         0.0       NaN         NaN   
36   2020/1/18      3.8      6.2      0.9         7.5       NaN         NaN   
40   2020/1/22      4.0      6.2      1.4         0.0       NaN         NaN   
45   2020/1/27      4.7      6.8      3.1         3.5       NaN         NaN   
56    2020/2/7      1.8      7.0     -4.3         0.0       NaN         NaN   
..         ...      ...      ...      ...         ...       ...         ...   
261  2020/8/30     29.8     35.4     26.2         0.0       NaN         NaN   
243  2020/8/12     30.3     35.9     27.6         0.0       NaN         NaN   
246  2020/8/15     31.2     36.5     27.8         0.0       NaN         NaN   
244  2020/8/13     30.4     37.1     26.9         0.5       NaN         NaN   
248  2020/8/17     30.9     37.2     26.8         0.0       NaN         NaN   

     平均蒸気圧(hPa)  平均風速(m/s)  日照時間(時間)  
55          NaN        3.6       7.5  
36          NaN        2.5       0.0  
40          NaN        1.2       0.9  
45          NaN        1.6       0.0  
56          NaN        1.1       6.7  
..          ...        ...       ...  
261         NaN        1.9      11.4  
243         NaN        1.8       7.2  
246         NaN        1.5       8.7  
244         NaN        1.6       8.5  
248         NaN        1.7       9.4  

[367 rows x 10 columns]

In [102]:
df_people['nationality'].unique()

array(['Japan', 'America', 'Korea'], dtype=object)

In [103]:
df_people

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
2   35  31    Suzuki       Japan
3   16  20      John     America
4   28  11       Kim       Korea

In [105]:
pd.get_dummies(df_people['nationality'])

America  Japan  Korea
0        0      1      0
1        1      0      0
2        0      1      0
3        1      0      0
4        0      0      1

In [107]:
pd.get_dummies(df_people, columns=['nationality'])

age  id      name  nationality_America  nationality_Japan  \
0   26  13  Imanishi                    0                  1   
1   21  33      Mike                    1                  0   
2   35  31    Suzuki                    0                  1   
3   16  20      John                    1                  0   
4   28  11       Kim                    0                  0   

   nationality_Korea  
0                  0  
1                  0  
2                  0  
3                  0  
4                  1

In [108]:
df.isnull()

年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)  平均雲量(10分比)  \
1    False    False    False    False       False      True        True   
2    False    False    False    False       False      True        True   
3    False    False    False    False       False      True        True   
4    False    False    False    False       False      True        True   
5    False    False    False    False       False      True        True   
..     ...      ...      ...      ...         ...       ...         ...   
363  False    False    False    False       False      True        True   
364  False    False    False    False       False      True        True   
365  False    False    False    False       False      True        True   
366  False    False    False    False       False      True        True   
367  False    False    False    False       False      True        True   

     平均蒸気圧(hPa)  平均風速(m/s)  日照時間(時間)  
1          True      False     False  
2          True      False     False  
3          True      False     False  
4          True      False     False  
5          True      False     False  
..          ...        ...       ...  
363        True      False     False  
364        True      False     False  
365        True      False     False  
366        True      False     False  
367        True      False     False  

[367 rows x 10 columns]

In [109]:
df

年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)  平均雲量(10分比)  \
1    2019/12/14      9.3     15.9      3.2         0.0       NaN         NaN   
2    2019/12/15      7.8     11.1      4.0         0.0       NaN         NaN   
3    2019/12/16      6.9     12.5      1.3         0.0       NaN         NaN   
4    2019/12/17      8.2     10.3      5.7         2.0       NaN         NaN   
5    2019/12/18      9.9     15.0      4.8         0.0       NaN         NaN   
..          ...      ...      ...      ...         ...       ...         ...   
363  2020/12/10      8.7     11.1      6.0         0.5       NaN         NaN   
364  2020/12/11      9.2     13.8      3.5         0.0       NaN         NaN   
365  2020/12/12     10.4     14.0      8.0         0.0       NaN         NaN   
366  2020/12/13      8.6     14.4      4.4         0.0       NaN         NaN   
367  2020/12/14      7.8     12.2      4.4         0.0       NaN         NaN   

     平均蒸気圧(hPa)  平均風速(m/s)  日照時間(時間)  
1           NaN        2.0       8.9  
2           NaN        2.3       6.3  
3           NaN        1.1       8.9  
4           NaN        1.1       0.2  
5           NaN        1.2       4.3  
..          ...        ...       ...  
363         NaN        1.4       0.0  
364         NaN        0.8       4.3  
365         NaN        1.4       1.4  
366         NaN        1.0       5.5  
367         NaN        1.9       4.4  

[367 rows x 10 columns]

In [110]:
df.fillna(0).head()

年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)  平均雲量(10分比)  \
1  2019/12/14      9.3     15.9      3.2         0.0       0.0         0.0   
2  2019/12/15      7.8     11.1      4.0         0.0       0.0         0.0   
3  2019/12/16      6.9     12.5      1.3         0.0       0.0         0.0   
4  2019/12/17      8.2     10.3      5.7         2.0       0.0         0.0   
5  2019/12/18      9.9     15.0      4.8         0.0       0.0         0.0   

   平均蒸気圧(hPa)  平均風速(m/s)  日照時間(時間)  
1         0.0        2.0       8.9  
2         0.0        2.3       6.3  
3         0.0        1.1       8.9  
4         0.0        1.1       0.2  
5         0.0        1.2       4.3

In [111]:
df.dropna(axis=1)

年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  平均風速(m/s)  日照時間(時間)
1    2019/12/14      9.3     15.9      3.2         0.0        2.0       8.9
2    2019/12/15      7.8     11.1      4.0         0.0        2.3       6.3
3    2019/12/16      6.9     12.5      1.3         0.0        1.1       8.9
4    2019/12/17      8.2     10.3      5.7         2.0        1.1       0.2
5    2019/12/18      9.9     15.0      4.8         0.0        1.2       4.3
..          ...      ...      ...      ...         ...        ...       ...
363  2020/12/10      8.7     11.1      6.0         0.5        1.4       0.0
364  2020/12/11      9.2     13.8      3.5         0.0        0.8       4.3
365  2020/12/12     10.4     14.0      8.0         0.0        1.4       1.4
366  2020/12/13      8.6     14.4      4.4         0.0        1.0       5.5
367  2020/12/14      7.8     12.2      4.4         0.0        1.9       4.4

[367 rows x 7 columns]

In [112]:
df_iris = pd.read_csv('iris.csv')

In [113]:
df_iris.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [114]:
df_iris['Class'].value_counts()

Iris-versicolor    53
Iris-virginica     53
Iris-setosa        50
Name: Class, dtype: int64

In [116]:
df_iris.groupby('Class').mean()

sepal-length  sepal-width  petal-length  petal-width
Class                                                                
Iris-setosa          5.004255     3.434000      1.454000     0.244000
Iris-versicolor      6.403774     2.762264      4.307547     1.352830
Iris-virginica       6.937736     2.979245      5.526415     2.013208

In [117]:
df_iris.groupby('Class').median()

sepal-length  sepal-width  petal-length  petal-width
Class                                                                
Iris-setosa               5.0          3.4           1.5          0.2
Iris-versicolor           6.0          2.8           4.4          1.3
Iris-virginica            6.5          3.0           5.5          2.0

In [118]:
df.mean()

平均気温(℃)       16.213896
最高気温(℃)       20.466757
最低気温(℃)       12.536785
降水量の合計(mm)     3.882834
最深積雪(cm)            NaN
平均雲量(10分比)          NaN
平均蒸気圧(hPa)          NaN
平均風速(m/s)      1.848774
日照時間(時間)       5.118256
dtype: float64

In [119]:
df.median()

平均気温(℃)       15.3
最高気温(℃)       19.9
最低気温(℃)       10.9
降水量の合計(mm)     0.0
最深積雪(cm)       NaN
平均雲量(10分比)     NaN
平均蒸気圧(hPa)     NaN
平均風速(m/s)      1.7
日照時間(時間)       4.8
dtype: float64

In [120]:
df.std()

平均気温(℃)        7.597900
最高気温(℃)        7.771437
最低気温(℃)        8.147217
降水量の合計(mm)    10.198369
最深積雪(cm)            NaN
平均雲量(10分比)          NaN
平均蒸気圧(hPa)          NaN
平均風速(m/s)      0.704119
日照時間(時間)       4.237862
dtype: float64

In [121]:
df.max()

年月日           2020/9/9
平均気温(℃)           31.2
最高気温(℃)           37.2
最低気温(℃)           27.8
降水量の合計(mm)        77.5
最深積雪(cm)           NaN
平均雲量(10分比)         NaN
平均蒸気圧(hPa)         NaN
平均風速(m/s)          4.4
日照時間(時間)          13.5
dtype: object

In [122]:
df.min()

年月日           2019/12/14
平均気温(℃)              1.8
最高気温(℃)              5.5
最低気温(℃)             -4.3
降水量の合計(mm)           0.0
最深積雪(cm)             NaN
平均雲量(10分比)           NaN
平均蒸気圧(hPa)           NaN
平均風速(m/s)            0.7
日照時間(時間)             0.0
dtype: object