In [45]:
class Person:
    __nationality = 'Japan'
    
    def __init__(self, name):
        self.name = name
    
    def say_hello(self):
        print(f'こんにちは、私の国籍は、{self.__nationality}です。')
    
    def __say_my_name(self):
        print(f'私の名前は{self.name}です。')
    

In [46]:
imanishi = Person('今西')

In [47]:
imanishi.name

'今西'

In [48]:
imanishi.__nationality

AttributeError: 'Person' object has no attribute '__nationality'

In [49]:
imanishi.__say_my_name()

AttributeError: 'Person' object has no attribute '__say_my_name'

In [50]:
imanishi.say_hello()

こんにちは、私の国籍は、Japanです。


In [52]:
import os

In [53]:
os.system('ls -a')

1

In [54]:
print(os.popen('ls -a').read())

In [56]:
!ls -a

'ls' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。


In [41]:
cd pyworks

[WinError 2] 指定されたファイルが見つかりません。: 'pyworks'
C:\Users\takas\pyworks


In [42]:
file = open('sample.txt', encoding ='UTF-8')
text = file.read()
file.close()

In [43]:
print(text)

はじめまして、
こちらはいまにゅチャンネルです。
Pythonをつかいこなしていろんなことができるように、
一緒に学んでいきましょう。


In [44]:
with open('sample.txt', 'r', encoding ='UTF-8') as f:
    text = f.read()

In [45]:
print(text)

はじめまして、
こちらはいまにゅチャンネルです。
Pythonをつかいこなしていろんなことができるように、
一緒に学んでいきましょう。


In [55]:
import json

In [56]:
with open('sample.json', 'r', encoding = 'UTF-8') as f:
    data = json.load(f)
#withの引数の中は順番大事

In [57]:
data

{'store_name': '神田店',
 'items': [{'item_id': 0, 'item_name': 'コーラ'},
  {'item_id': 1, 'item_name': '唐揚げ弁当'},
  {'item_id': 2, 'item_name': '週刊誌'}]}

In [58]:
data['store_name']

'神田店'

In [59]:
import os

In [66]:
for curDir, dirs, files in os.walk('.'):
    for file in files:
        print(f'{curDir}/{file}')

./fibonacci.ipynb
./keras練習.ipynb
./sample.json
./sample.txt
./Untitled.ipynb
./XGboost.ipynb
./XGboostで回帰.ipynb
./ベイズ更新の練習.ipynb
.\.ipynb_checkpoints/fibonacci-checkpoint.ipynb
.\.ipynb_checkpoints/keras練習-checkpoint.ipynb
.\.ipynb_checkpoints/Untitled-checkpoint.ipynb
.\.ipynb_checkpoints/XGboost-checkpoint.ipynb
.\.ipynb_checkpoints/XGboostで回帰-checkpoint.ipynb
.\.ipynb_checkpoints/ベイズ更新の練習-checkpoint.ipynb
.\kerasstudy/data_type.ipynb
.\kerasstudy/FashionMNIST_3layer.ipynb
.\kerasstudy/MNIST_3layer.ipynb
.\kerasstudy/MNIST_3layer_t.ipynb
.\kerasstudy/●Udemy_kaggleで学ぼう pythonとkerasで学ぶディープラーニング.txt
.\kerasstudy\.ipynb_checkpoints/MNIST_3d-checkpoint.ipynb
.\kerasstudy\.ipynb_checkpoints/データ型-checkpoint.ipynb
.\Udemy_datascientist/python.ipynb
.\Udemy_datascientist/●_【データサイエンティスト育成講座】Python初心者も歓迎！機械学習を駆使してビジネス課題を解決するためのエッセンス.txt
.\Udemy_datascientist\.ipynb_checkpoints/python-checkpoint.ipynb
.\Udemy_datascientist\lesson2_蜈ｱ譛臥畑/.DS_Store
.\Udemy_datascientist\lesson2_蜈ｱ譛臥畑/Pipfile
.\Ud

In [70]:
lists = os.listdir('.')
lists.sort()
lists

['.ipynb_checkpoints',
 'Udemy_datascientist',
 'Untitled.ipynb',
 'XGboost.ipynb',
 'XGboostで回帰.ipynb',
 'fibonacci.ipynb',
 'kerasstudy',
 'keras練習.ipynb',
 'sample.json',
 'sample.txt',
 'ベイズ更新の練習.ipynb']

In [71]:
os.path.abspath('Untitled.ipynb')

'C:\\Users\\takas\\pyworks\\Untitled.ipynb'

In [72]:
os.path.basename('Untitled.ipynb')

'Untitled.ipynb'

In [74]:
cd pyworks

C:\Users\takas\pyworks


In [77]:
os.path.exists('Untitled.ipynb')

True

In [79]:
os.path.isdir('Udemy_datascientist')

True

In [80]:
os.path.isfile('Untitled.ipynb')

True

In [81]:
for curDir, dirs, files in os.walk('.'):
    for file in files:
        print(os.path.join(curDir, file))

.\fibonacci.ipynb
.\keras練習.ipynb
.\sample.json
.\sample.txt
.\Untitled.ipynb
.\XGboost.ipynb
.\XGboostで回帰.ipynb
.\ベイズ更新の練習.ipynb
.\.ipynb_checkpoints\fibonacci-checkpoint.ipynb
.\.ipynb_checkpoints\keras練習-checkpoint.ipynb
.\.ipynb_checkpoints\Untitled-checkpoint.ipynb
.\.ipynb_checkpoints\XGboost-checkpoint.ipynb
.\.ipynb_checkpoints\XGboostで回帰-checkpoint.ipynb
.\.ipynb_checkpoints\ベイズ更新の練習-checkpoint.ipynb
.\kerasstudy\data_type.ipynb
.\kerasstudy\FashionMNIST_3layer.ipynb
.\kerasstudy\MNIST_3layer.ipynb
.\kerasstudy\MNIST_3layer_t.ipynb
.\kerasstudy\●Udemy_kaggleで学ぼう pythonとkerasで学ぶディープラーニング.txt
.\kerasstudy\.ipynb_checkpoints\MNIST_3d-checkpoint.ipynb
.\kerasstudy\.ipynb_checkpoints\データ型-checkpoint.ipynb
.\Udemy_datascientist\python.ipynb
.\Udemy_datascientist\●_【データサイエンティスト育成講座】Python初心者も歓迎！機械学習を駆使してビジネス課題を解決するためのエッセンス.txt
.\Udemy_datascientist\.ipynb_checkpoints\python-checkpoint.ipynb
.\Udemy_datascientist\lesson2_蜈ｱ譛臥畑\.DS_Store
.\Udemy_datascientist\lesson2_蜈ｱ譛臥畑\Pipfile
.\Ud

In [82]:
os.mkdir('imanyu')

In [83]:
os.remove('消したいファイル名.txt')

PermissionError: [WinError 5] アクセスが拒否されました。: 'imanyu'

In [84]:
os.rename('imanyu', 'kobe')

In [85]:
os.environ['PATH']

'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\MATLAB\\R2020a\\bin;%SystemRoot%\\system32;%SystemRoot%;%SystemRoot%\\System32\\Wbem;%SYSTEMROOT%\\System32\\WindowsPowerShell\\v1.0\\;%SYSTEMROOT%\\System32\\OpenSSH\\;C:\\Users\\takas\\anaconda3;C:\\Users\\takas\\anaconda3\\Library\\mingw-w64\\bin;C:\\Users\\takas\\anaconda3\\Library\\usr\\bin;C:\\Users\\takas\\anaconda3\\Library\\bin;C:\\Users\\takas\\anaconda3\\Scripts;C:\\Users\\takas\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\takas\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;'

In [87]:
os.system('ls -a')

1

In [89]:
print(os.popen('ls -a').read())

In [90]:
!ls -a

'ls' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。


In [91]:
import numpy as np

In [94]:
a = np.array([1, 2, 3, 4])

In [95]:
a

array([1, 2, 3, 4])

In [96]:
a.shape

(4,)

In [98]:
b = np.array([[1, 2], 
              [3, 4]])

In [99]:
b.shape

(2, 2)

In [101]:
c = np.zeros(8)

In [102]:
c.shape

(8,)

In [106]:
d = np.zeros((4,3))
#引数の中にタプル()を入れることを忘れずに

In [107]:
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [108]:
d.shape

(4, 3)

In [111]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])